"""
Python surface of the rspyts basic example.

Notes:
    Everything under ``generated`` is produced by ``rspyts generate`` from
    the Rust crate next door; this package just re-exports it. Hand-written
    helpers would live here, importing from the generated modules — never
    the reverse.
"""

from . import generated
from .generated import (
    EXACT_BOUNDS,
    MAX_EXACT_U64,
    MAX_WINDOW,
    ROUNDING_MODES,
    BasicError,
    BasicErrorEmptyInput,
    BasicErrorNotANumber,
    BasicErrorSequenceTooLarge,
    BasicErrorTooManyValues,
    BasicErrorUnreadableFile,
    BasicErrorZeroFactor,
    BinaryPacket,
    Counter,
    ExactNumbers,
    PacketId,
    ParsedNumber,
    ParsedNumberDecimal,
    ParsedNumberInteger,
    Rounding,
    Summary,
    TransferState,
    TransferStateComplete,
    TransferStatePending,
    annotate,
    echo_binary_packet,
    echo_bytes,
    echo_exact_numbers,
    echo_exact_pair,
    echo_transfer_state,
    load_values,
    parse_number,
    round_value,
    scale,
    simulate_panic,
    summarize,
    validate_sequence,
)

__all__ = [
    "EXACT_BOUNDS",
    "MAX_EXACT_U64",
    "MAX_WINDOW",
    "ROUNDING_MODES",
    "BasicError",
    "BasicErrorEmptyInput",
    "BasicErrorNotANumber",
    "BasicErrorSequenceTooLarge",
    "BasicErrorTooManyValues",
    "BasicErrorUnreadableFile",
    "BasicErrorZeroFactor",
    "BinaryPacket",
    "Counter",
    "ExactNumbers",
    "PacketId",
    "ParsedNumber",
    "ParsedNumberDecimal",
    "ParsedNumberInteger",
    "Rounding",
    "Summary",
    "TransferState",
    "TransferStateComplete",
    "TransferStatePending",
    "annotate",
    "echo_binary_packet",
    "echo_bytes",
    "echo_exact_numbers",
    "echo_exact_pair",
    "echo_transfer_state",
    "generated",
    "load_values",
    "parse_number",
    "round_value",
    "scale",
    "simulate_panic",
    "summarize",
    "validate_sequence",
]
