use std::ffi::OsString;
use std::path::Path;
use std::process::Command;

use serde_json::Value;

fn binary() -> &'static str {
    env!("CARGO_BIN_EXE_rspyts")
}

fn assert_project_layout(project: &Path) {
    let mut expected = [
        ".gitignore",
        "Cargo.toml",
        "rspyts.toml",
        "src/lib.rs",
        "src-py/.gitignore",
        "src-py/pyproject.toml",
        "src-py/hello_world/__init__.py",
        "src-ts/package.json",
        "src-ts/.gitignore",
        "src-ts/tsconfig.json",
        "src-ts/hello-world/index.ts",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect::<Vec<_>>();
    let mut actual = Vec::new();
    collect_project_files(project, project, &mut actual);
    expected.sort();
    actual.sort();
    assert_eq!(actual, expected);
    let python_init = std::fs::read_to_string(project.join("src-py/hello_world/__init__.py"))
        .expect("read Python entrypoint");
    assert_eq!(
        python_init,
        "from .models import *\nfrom .models import __all__ as __models__\n\nfrom .api import *\nfrom .api import __all__ as __api__\n\n__all__ = [*__models__, *__api__]\n"
    );
    assert_eq!(
        std::fs::read_to_string(project.join("src-ts/hello-world/index.ts"))
            .expect("read TypeScript entrypoint"),
        "export * from \"./models.js\";\nexport * from \"./api.js\";\n"
    );
    let root_gitignore =
        std::fs::read_to_string(project.join(".gitignore")).expect("read root ignore");
    assert!(
        root_gitignore
            .lines()
            .any(|line| line == "/.rspyts-build.lock")
    );
    let ownership =
        std::fs::read_to_string(project.join("rspyts.toml")).expect("read rspyts config");
    assert!(ownership.starts_with("# rspyts application configuration"));
    assert!(ownership.contains("# name = \"my-application\""));
    assert!(ownership.contains("# additional_packages = [\"my-shared-api\"]"));
    assert!(ownership.contains("# python_package = \"my_application\""));
    assert!(ownership.contains("# typescript_package = \"my-application\""));
    assert!(ownership.contains("# gitignore = false"));
    let ownership: toml::Value = ownership.parse().expect("parse generated ownership TOML");
    assert!(ownership.get("version").is_none());
    assert_eq!(
        ownership["generated"]["source_fingerprint"].as_str(),
        Some("")
    );
    assert_eq!(
        ownership["generated"]["python"]["files"]
            .as_array()
            .map(Vec::len),
        Some(1)
    );
    assert_eq!(
        ownership["generated"]["python"]["native_modules"]
            .as_array()
            .map(Vec::len),
        Some(0)
    );
    assert_eq!(
        ownership["generated"]["python"]["files"][0].as_str(),
        Some("src-py/.gitignore")
    );
    assert_eq!(
        ownership["generated"]["typescript"]["files"][0].as_str(),
        Some("src-ts/.gitignore")
    );
    let python_gitignore =
        std::fs::read_to_string(project.join("src-py/.gitignore")).expect("read Python ignore");
    assert!(python_gitignore.starts_with("# =================================="));
    assert!(python_gitignore.contains("AUTO-GENERATED BY rspyts - DO NOT EDIT"));
    assert!(python_gitignore.contains("/hello_world/api.py"));
    assert!(python_gitignore.contains("/hello_world/native/native.abi3.so"));
    assert!(python_gitignore.contains("/hello_world/native/native.pyd"));
    assert!(!python_gitignore.contains("pyproject.toml"));
    assert!(!python_gitignore.contains("/hello_world/__init__.py"));
    assert!(python_gitignore.contains("/hello_world/native/__init__.py"));
    let typescript_gitignore =
        std::fs::read_to_string(project.join("src-ts/.gitignore")).expect("read TypeScript ignore");
    assert!(typescript_gitignore.starts_with("# =================================="));
    assert!(typescript_gitignore.contains("AUTO-GENERATED BY rspyts - DO NOT EDIT"));
    assert!(typescript_gitignore.contains("/hello-world/api.ts"));
    assert!(typescript_gitignore.contains("/build/hello-world/native/native_bg.wasm"));
    assert!(!typescript_gitignore.contains("package.json"));
    assert!(!typescript_gitignore.contains("/hello-world/index.ts"));
    assert_eq!(
        ownership["generated"]["typescript"]["files"]
            .as_array()
            .map(Vec::len),
        Some(1)
    );
    let rust = std::fs::read_to_string(project.join("src/lib.rs")).expect("read Rust source");
    assert!(rust.contains("pub fn greet"));
    assert!(!rust.contains("application!"));
    assert!(!project.join("crates").exists());
    let python_project =
        std::fs::read_to_string(project.join("src-py/pyproject.toml")).expect("Python manifest");
    assert!(python_project.contains("name = \"hello-world\"\nversion = \"0.1.0\""));
    assert!(python_project.contains("rspyts never modifies this file"));
    assert!(python_project.contains("build-backend = \"pdm.backend\""));
    assert!(python_project.contains("includes = [\"hello_world\"]"));
    assert!(python_project.contains("is-purelib = false"));
    assert!(!project.join("src-py/setup.py").exists());
    assert!(!project.join("src-py/setup.cfg").exists());
    let typescript_package =
        std::fs::read_to_string(project.join("src-ts/package.json")).expect("npm manifest");
    assert!(typescript_package.contains("\"version\": \"0.1.0\""));
    assert!(typescript_package.contains("\"build\": \"tsc\""));
    assert!(typescript_package.contains("rspyts never modifies this file"));
    let typescript_config =
        std::fs::read_to_string(project.join("src-ts/tsconfig.json")).expect("TypeScript config");
    assert!(typescript_config.contains("rspyts never modifies this file"));
    assert!(!project.join("src-ts/scripts").exists());
}

fn collect_project_files(root: &Path, current: &Path, files: &mut Vec<String>) {
    for entry in std::fs::read_dir(current).expect("read initialized project") {
        let path = entry.expect("read initialized entry").path();
        if path.is_dir() {
            collect_project_files(root, &path, files);
        } else {
            files.push(
                path.strip_prefix(root)
                    .expect("project-relative path")
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

#[test]
fn output_argument_is_rejected() {
    let mut stdout = Vec::new();
    let mut stderr = Vec::new();
    let error = rspyts_cli::run_with(
        ["rspyts", "build", "--output", "somewhere"],
        &mut stdout,
        &mut stderr,
    )
    .expect_err("removed output option must fail");

    assert!(error.to_string().contains("unexpected argument '--output'"));
    assert!(stdout.is_empty());
    assert!(stderr.is_empty());
}

#[test]
fn manifest_path_argument_is_rejected() {
    let mut stdout = Vec::new();
    let mut stderr = Vec::new();
    let error = rspyts_cli::run_with(
        ["rspyts", "build", "--manifest-path", "Cargo.toml"],
        &mut stdout,
        &mut stderr,
    )
    .expect_err("removed manifest path option must fail");

    assert!(
        error
            .to_string()
            .contains("unexpected argument '--manifest-path'")
    );
    assert!(stdout.is_empty());
    assert!(stderr.is_empty());
}

#[test]
fn explicit_entry_point_captures_output_and_creates_a_project() {
    let directory = tempfile::tempdir().expect("temporary directory");
    let project = directory.path().join("hello-world");
    let mut stdout = Vec::new();
    let mut stderr = Vec::new();

    rspyts_cli::run_with(
        [
            OsString::from("rspyts"),
            OsString::from("init"),
            project.clone().into_os_string(),
        ],
        &mut stdout,
        &mut stderr,
    )
    .expect("init succeeds");

    assert!(stderr.is_empty());
    let report: Value = serde_json::from_slice(&stdout).expect("JSON report");
    assert_eq!(report["status"], "ok");
    assert_eq!(report["project"], project.to_string_lossy().as_ref());
    assert_project_layout(&project);
}

#[test]
fn init_runs_end_to_end_through_the_binary() {
    let directory = tempfile::tempdir().expect("temporary directory");
    let project = directory.path().join("hello-world");

    let output = Command::new(binary())
        .arg("init")
        .arg(&project)
        .output()
        .expect("run rspyts");

    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(output.stderr.is_empty());
    let report: Value = serde_json::from_slice(&output.stdout).expect("JSON report");
    assert_eq!(report["status"], "ok");
    assert_project_layout(&project);
}

#[test]
fn init_applies_one_version_to_every_package_manifest() {
    let directory = tempfile::tempdir().expect("temporary directory");
    let project = directory.path().join("versioned-app");

    let output = Command::new(binary())
        .arg("init")
        .arg(&project)
        .args(["--version", "1.2.3"])
        .output()
        .expect("run rspyts");

    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    for (path, needle) in [
        ("Cargo.toml", "version = \"1.2.3\""),
        ("src-py/pyproject.toml", "version = \"1.2.3\""),
        ("src-ts/package.json", "\"version\": \"1.2.3\""),
    ] {
        let source = std::fs::read_to_string(project.join(path)).expect("read package manifest");
        assert!(source.contains(needle), "{path} did not contain {needle}");
    }
}

#[test]
fn init_rejects_an_invalid_version_without_creating_a_project() {
    let directory = tempfile::tempdir().expect("temporary directory");
    let project = directory.path().join("versioned-app");

    let output = Command::new(binary())
        .arg("init")
        .arg(&project)
        .args(["--version", "not-a-version"])
        .output()
        .expect("run rspyts");

    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("invalid value 'not-a-version'"));
    assert!(!project.exists());
}

#[test]
fn invalid_init_fails_without_leaving_a_partial_project() {
    let directory = tempfile::tempdir().expect("temporary directory");
    let project = directory.path().join("Invalid_name");

    let output = Command::new(binary())
        .arg("init")
        .arg(&project)
        .output()
        .expect("run rspyts");

    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
    assert!(
        String::from_utf8_lossy(&output.stderr)
            .contains("must use lower-case letters, numbers, and single hyphens")
    );
    assert!(!project.exists());
}
