/**
 * rspyts TypeScript runtime — the support library for code generated by
 * `rspyts generate` (see `docs/design/codegen.md` §5.1 in the repository).
 *
 * This is the complete public surface; generated code imports exactly
 * these names and nothing else.
 */

export { instantiate, type BridgeModule } from "./module.js";
export {
  callFn,
  callDrop,
  floatFromWire,
  i64FromWire,
  i64ToWire,
  jsonFromWire,
  u64FromWire,
  u64ToWire,
  type SliceArg,
} from "./call.js";
export { wireBuffer } from "./envelope.js";
export {
  InstancePoisonedError,
  RspytsError,
  RspytsPanicError,
  StaleHandleError,
  type BridgeErrorRegistry,
  registerError,
} from "./errors.js";
